### PR TITLE
Fix auth token

### PR DESCRIPTION
**Pull request by i-be-snek**
The issue was related to auth GET requests needing to take in the `params` parameter, not `json`.

### CODE REVIEW

**Comment by i-be-snek** [comment]
Sorry about the clutter, just learning how to deal with forks for the first time in a while.

**Comment by db0** [comment]
Did you mean to close this then?

**Comment by i-be-snek** [comment]
> Did you mean to close this then?

yes! :)

**Comment by i-be-snek** [comment]
The changes are reflected here: https://github.com/db0/pythorhead/pull/34
I accidentally started a PR from my fork to merge into this repo instead of my own forked one :sweat:

**Pull request closed without merging**
