### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by NicKoehler**
I'm interested in helping with this library.

I followed [this](https://join-lemmy.org/api/) to implement more functionalities about posts.
Also I added types and some docs to post methods.

Fell free to review my changes to your api if you want me to change something.

### CODE REVIEW

**Comment by db0** [comment]
Thanks for helping!

One suggestion what do you think about making the `post.__call__()` effectively call `.create()`? This way one can still call `lemmy.post()`.

What I don't quite like is copying the authentication values into every class. I'd rather put the authentication into its own class singleton and have every class import it, or something similar.

**Comment by NicKoehler** [comment]
What do you think of something like this?

**Comment by db0** [comment]
Assuming you're tested it, it looks good to me. Just change the `post` class to `Post` to be  CamelCase as per python naming suggestions.

**Comment by NicKoehler** [comment]
I didn't test everything, I need to create a dummy instance first, I'll test it and let you know

**Comment by db0** [comment]
LGTM. Mark it as ready when you're done

**Pull request merged**
